// Estado real do Campeonato do Nordeste Argentino (NEA) após a 7ª rodada,
// usado para começar a temporada já em andamento com a tabela:
// 1º Taraguy 32, 2º Aranduroga 29, 3º San Patricio 22, 4º Curne 21,
// 5º Curda 20, 6º San José 15, 7º Regatas 11, 8º Sixty 10, 9º Aguará 9,
// 10º Capri 0 (todos com 7 jogos disputados).
export const NEA_SEED_MATCHES = [
  {round: 1, home: 'ARG-TAR', away: 'ARG-SNP', scoreHome: 17, scoreAway: 17},
  {round: 1, home: 'ARG-ARA', away: 'ARG-AGU', scoreHome: 29, scoreAway: 10},
  {round: 1, home: 'ARG-REG', away: 'ARG-CNE', scoreHome: 18, scoreAway: 18},
  {round: 1, home: 'ARG-CUR', away: 'ARG-CAP', scoreHome: 26, scoreAway: 11},
  {round: 1, home: 'ARG-SNJ', away: 'ARG-SIX', scoreHome: 11, scoreAway: 30},
  {round: 2, home: 'ARG-AGU', away: 'ARG-TAR', scoreHome: 11, scoreAway: 35},
  {round: 2, home: 'ARG-CNE', away: 'ARG-SNP', scoreHome: 36, scoreAway: 12},
  {round: 2, home: 'ARG-CAP', away: 'ARG-ARA', scoreHome: 13, scoreAway: 34},
  {round: 2, home: 'ARG-SIX', away: 'ARG-REG', scoreHome: 34, scoreAway: 10},
  {round: 2, home: 'ARG-SNJ', away: 'ARG-CUR', scoreHome: 34, scoreAway: 12},
  {round: 3, home: 'ARG-TAR', away: 'ARG-CNE', scoreHome: 29, scoreAway: 13},
  {round: 3, home: 'ARG-AGU', away: 'ARG-CAP', scoreHome: 24, scoreAway: 11},
  {round: 3, home: 'ARG-SNP', away: 'ARG-SIX', scoreHome: 34, scoreAway: 11},
  {round: 3, home: 'ARG-ARA', away: 'ARG-SNJ', scoreHome: 19, scoreAway: 13},
  {round: 3, home: 'ARG-REG', away: 'ARG-CUR', scoreHome: 13, scoreAway: 35},
  {round: 4, home: 'ARG-CAP', away: 'ARG-TAR', scoreHome: 8, scoreAway: 28},
  {round: 4, home: 'ARG-SIX', away: 'ARG-CNE', scoreHome: 9, scoreAway: 17},
  {round: 4, home: 'ARG-SNJ', away: 'ARG-AGU', scoreHome: 14, scoreAway: 36},
  {round: 4, home: 'ARG-CUR', away: 'ARG-SNP', scoreHome: 29, scoreAway: 13},
  {round: 4, home: 'ARG-REG', away: 'ARG-ARA', scoreHome: 13, scoreAway: 29},
  {round: 5, home: 'ARG-TAR', away: 'ARG-SIX', scoreHome: 34, scoreAway: 13},
  {round: 5, home: 'ARG-CAP', away: 'ARG-SNJ', scoreHome: 8, scoreAway: 26},
  {round: 5, home: 'ARG-CNE', away: 'ARG-CUR', scoreHome: 38, scoreAway: 14},
  {round: 5, home: 'ARG-AGU', away: 'ARG-REG', scoreHome: 13, scoreAway: 30},
  {round: 5, home: 'ARG-SNP', away: 'ARG-ARA', scoreHome: 38, scoreAway: 14},
  {round: 6, home: 'ARG-SNJ', away: 'ARG-TAR', scoreHome: 8, scoreAway: 29},
  {round: 6, home: 'ARG-CUR', away: 'ARG-SIX', scoreHome: 28, scoreAway: 11},
  {round: 6, home: 'ARG-REG', away: 'ARG-CAP', scoreHome: 24, scoreAway: 12},
  {round: 6, home: 'ARG-ARA', away: 'ARG-CNE', scoreHome: 27, scoreAway: 11},
  {round: 6, home: 'ARG-SNP', away: 'ARG-AGU', scoreHome: 31, scoreAway: 14},
  {round: 7, home: 'ARG-TAR', away: 'ARG-CUR', scoreHome: 36, scoreAway: 14},
  {round: 7, home: 'ARG-SNJ', away: 'ARG-REG', scoreHome: 36, scoreAway: 12},
  {round: 7, home: 'ARG-SIX', away: 'ARG-ARA', scoreHome: 8, scoreAway: 28},
  {round: 7, home: 'ARG-CAP', away: 'ARG-SNP', scoreHome: 10, scoreAway: 29},
  {round: 7, home: 'ARG-CNE', away: 'ARG-AGU', scoreHome: 36, scoreAway: 14},
];
